In [2]:
import pandas as pd
from pandasql import sqldf

In [6]:
TABLE_NAME1 = "customer_table"
DATA_PATH1 = "../data/" + TABLE_NAME1 + ".csv"

TABLE_NAME2 = "address_table"
DATA_PATH2 = "../data/" + TABLE_NAME2 + ".csv"
df1 = pd.read_csv(DATA_PATH1)
df2 = pd.read_csv(DATA_PATH2)
# Important: assign dataframe to variable matching table name
df_table1 = df1
df_table2 = df2
query = """
SELECT email, district FROM df_table1
INNER JOIN df_table2
	ON df_table1.address_id = df_table2.address_id
WHERE df_table2.district = 'California';
"""

result = sqldf(query, globals())
result.head(10)

                                  email    district
0   patricia.johnson@sakilacustomer.org  California
1        betty.white@sakilacustomer.org  California
2      alice.stewart@sakilacustomer.org  California
3      rosa.reynolds@sakilacustomer.org  California
4         renee.lane@sakilacustomer.org  California
5   kristin.johnston@sakilacustomer.org  California
6  cassandra.walters@sakilacustomer.org  California
7        jacob.lance@sakilacustomer.org  California
8     rene.mcalister@sakilacustomer.org  California

In [10]:
TABLE_NAME1 = "film_actor_table"
TABLE_NAME2 = "actor_table"
TABLE_NAME3 = "film_table"

DATA_PATH1 = "../data/" + TABLE_NAME1 + ".csv"
DATA_PATH2 = "../data/" + TABLE_NAME2 + ".csv"
DATA_PATH3 = "../data/" + TABLE_NAME3 + ".csv"

df1 = pd.read_csv(DATA_PATH1)
df2 = pd.read_csv(DATA_PATH2)
df3 = pd.read_csv(DATA_PATH3)
# Important: assign dataframe to variable matching table name
df_table1 = df1
df_table2 = df2
df_table3 = df3
TABLE_NAME1 = "film_actor_table"
TABLE_NAME2 = "actor_table"
TABLE_NAME3 = "film_table"

DATA_PATH1 = "../data/" + TABLE_NAME1 + ".csv"
DATA_PATH2 = "../data/" + TABLE_NAME2 + ".csv"
DATA_PATH3 = "../data/" + TABLE_NAME3 + ".csv"

df1 = pd.read_csv(DATA_PATH1)
df2 = pd.read_csv(DATA_PATH2)
df3 = pd.read_csv(DATA_PATH3)
# Important: assign dataframe to variable matching table name
df_table1 = df1
df_table2 = df2
df_table3 = df3

query = """
SELECT first_name, last_name, title
FROM df_table2
INNER JOIN df_table1
    ON df_table2.actor_id = df_table1.actor_id
INNER JOIN df_table3
    ON df_table1.film_id = df_table3.film_id
WHERE first_name = 'Nick' AND last_name = 'Wahlberg'; 
"""

result = sqldf(query, globals())
result.head(5)

  first_name last_name             title
0       Nick  Wahlberg  Adaptation Holes
1       Nick  Wahlberg     Apache Divine
2       Nick  Wahlberg         Baby Hall
3       Nick  Wahlberg    Bull Shawshank
4       Nick  Wahlberg   Chainsaw Uptown